theme: jekyll-theme-cayman
title: Безопасность для всех
description: Подкаст об информационной безопасности
timezone: Europe/Moscow
owner: "Андрей Данин"
email: "danindrey@mail.ru"
podcast:
    image: "/assets/images/podcast_1400.jpg"
    subtitle: "Подкаст о технологиях и новостях из мира информационной безопасности."
    copyright: "2018-2020 Андрей Данин"
excerpt_separator: <!--more-->

url: "https://stuw.github.io"
paginate: 8
plugins:
  - jekyll-sitemap
  - jekyll-paginate
